# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, default='', help_text="Donor's name", max_length=256, verbose_name='Donor Name')),
                ('integration_date', models.DateField(default=datetime.date(2017, 3, 7), help_text='Date when the donor is integrated into Vifac', verbose_name='Integration Date')),
                ('reference', models.CharField(blank=True, default='', help_text='Whoever introduced the donor to Vifac', max_length=256, verbose_name='Reference')),
                ('address', models.OneToOneField(help_text="Donor's address", on_delete=django.db.models.deletion.CASCADE, to='donors.Address', verbose_name='Address')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donors.Category', verbose_name='Category')),
                ('contacts', models.ForeignKey(help_text='Contact information for the donor', on_delete=django.db.models.deletion.CASCADE, to='donors.Contact', verbose_name='Contact Information')),
                ('donation', models.ForeignKey(blank=True, help_text='Whatever the donation may be', on_delete=django.db.models.deletion.CASCADE, to='donors.Donation', verbose_name='Donation')),
            ],
        ),
    ]
