# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.ForeignKey(help_text='How one would classify the donation: money, food, etc.', on_delete=django.db.models.deletion.CASCADE, to='donors.Category', verbose_name='Category'),
        ),
    ]
