# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 07:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_auto_20170307_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='integration_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 7, 7, 57, 39, 708518), help_text='Date when the donor is integrated into Vifac', verbose_name='Integration Date'),
        ),
    ]
