# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_auto_20170307_0757'),
        ('donors', '0002_auto_20170317_0305'),
    ]

    operations = [
    ]
